ninhthuanntnt/HighBlogApi

src/main/java/com/high/highblog/api/FileController.java
src/main/java/com/high/highblog/api/user/TagListController.java
src/main/java/com/high/highblog/bloc/TagBloc.java
src/main/java/com/high/highblog/config/WebConfig.java
src/main/java/com/high/highblog/model/dto/response/TagRes.java
src/main/java/com/high/highblog/model/entity/Tag.java
src/main/java/com/high/highblog/model/mapper/TagMapper.java
src/main/java/com/high/highblog/repository/TagRepository.java
src/main/java/com/high/highblog/service/TagService.java
src/main/resources/config/liquibase_ext/changelog/20210321163200_changelog.xml
src/main/resources/config/liquibase_ext/data/hb_tags.csv
src/main/resources/config/liquibase_ext/master.xml

- Create api to fetch list tags
- Update cors config

[BE][USER] Create api to fetch list tags

---

.gitignore
docker-compose.yml
src/main/java/com/high/highblog/api/FileUploadController.java
src/main/java/com/high/highblog/bloc/FileBloc.java
src/main/java/com/high/highblog/model/dto/request/ImageUploadReq.java
src/main/java/com/high/highblog/model/dto/response/CkImageUploadRes.java
src/main/java/com/high/highblog/model/dto/response/ImageUploadRes.java
src/main/java/com/high/highblog/model/mapper/FileMapper.java

[BE][USER] Fix bug wrong param for ck upload image

---

auto_deploy_bash

[BE] Create bash to deloy automatically

---

src/main/java/com/high/highblog/api/user/PostCrudController.java
src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/mapper/PostMapper.java
src/main/java/com/high/highblog/mapper/TagMapper.java
src/main/java/com/high/highblog/model/dto/response/CategoryRes.java
src/main/java/com/high/highblog/model/dto/response/CkImageUploadRes.java
src/main/java/com/high/highblog/model/dto/response/ImageUploadRes.java
src/main/java/com/high/highblog/model/dto/response/PostDetailRes.java
src/main/java/com/high/highblog/model/entity/Post.java
src/main/java/com/high/highblog/model/entity/PostTag.java
src/main/java/com/high/highblog/repository/PostTagRepository.java
src/main/java/com/high/highblog/repository/RoleRepository.java
src/main/java/com/high/highblog/service/PostService.java
src/main/java/com/high/highblog/service/PostTagService.java

- Create api to get post detail to edit
- Update security

[BE][USER] Create api to get post detail to edit

---

build.gradle
gradle.properties
src/main/java/com/high/highblog/api/user/PostCrudController.java
src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/mapper/PostMapper.java
src/main/java/com/high/highblog/mapper/PostTagMapper.java
src/main/java/com/high/highblog/mapper/TagMapper.java
src/main/java/com/high/highblog/model/dto/request/PostUpdateReq.java
src/main/java/com/high/highblog/repository/PostTagRepository.java
src/main/java/com/high/highblog/service/PostService.java
src/main/java/com/high/highblog/service/PostTagService.java

[BE][USER] Create api to update post

---

src/main/java/com/high/highblog/api/common/PostCrudController.java
src/main/java/com/high/highblog/api/common/RegisterController.java
src/main/java/com/high/highblog/api/common/TagListController.java
src/main/java/com/high/highblog/api/user/PostCrudController.java
src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/mapper/PostMapper.java
src/main/java/com/high/highblog/model/dto/response/UserPostDetailRes.java
src/main/java/com/high/highblog/repository/PostRepository.java
src/main/java/com/high/highblog/service/PostService.java

- Created api to get post detail
- Update logic to get post detail for current user

[BE][VIEWER] Create api to get post detail

---

src/main/java/com/high/highblog/api/common/PostListController.java
src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/bloc/PostListBloc.java
src/main/java/com/high/highblog/helper/PaginationHelper.java
src/main/java/com/high/highblog/mapper/PostMapper.java
src/main/java/com/high/highblog/model/dto/request/BasePaginationReq.java
src/main/java/com/high/highblog/model/dto/response/BasePaginationRes.java
src/main/java/com/high/highblog/model/dto/response/PostRes.java
src/main/java/com/high/highblog/repository/PostTagRepository.java
src/main/java/com/high/highblog/service/PostService.java
src/main/java/com/high/highblog/service/PostTagService.java

- Create api to fetch list post

[BE][VIEWER] Create api to fetch list post

---

src/main/java/com/high/highblog/api/common/PostListController.java
src/main/java/com/high/highblog/api/user/PostCrudController.java
src/main/java/com/high/highblog/bloc/PostListBloc.java
src/main/java/com/high/highblog/helper/DateTimeHelper.java
src/main/java/com/high/highblog/helper/PaginationHelper.java
src/main/java/com/high/highblog/mapper/PostMapper.java
src/main/java/com/high/highblog/model/dto/request/BasePaginationReq.java
src/main/java/com/high/highblog/model/dto/request/LoginReq.java
src/main/java/com/high/highblog/model/dto/request/PostCreateReq.java
src/main/java/com/high/highblog/model/dto/request/PostSearchReq.java
src/main/java/com/high/highblog/model/dto/request/RegisterReq.java
src/main/java/com/high/highblog/model/dto/response/ErrorMessageRes.java
src/main/java/com/high/highblog/model/dto/response/PostDetailRes.java
src/main/java/com/high/highblog/model/dto/response/PostDetailToUpdateRes.java
src/main/java/com/high/highblog/model/dto/response/PostRes.java
src/main/java/com/high/highblog/model/dto/response/ProfileRes.java
src/main/java/com/high/highblog/model/dto/response/TokenRes.java
src/main/java/com/high/highblog/model/dto/response/UserInPostRes.java
src/main/java/com/high/highblog/model/entity/Post.java
src/main/java/com/high/highblog/repository/PostRepository.java
src/main/java/com/high/highblog/repository/PostTagRepository.java
src/main/java/com/high/highblog/repository/UserRepository.java
src/main/java/com/high/highblog/service/PostService.java
src/main/java/com/high/highblog/service/PostTagService.java
src/main/java/com/high/highblog/service/UserService.java
src/main/resources/application.yml
src/main/resources/config/liquibase/changelog/20210326151200_changelog.xml

- Create api to search posts
- Update api to fetch list posts
- Update config to support utf-8

[BE][VIEWER] Create api to search post

---

src/main/java/com/high/highblog/api/common/CommentListController.java
src/main/java/com/high/highblog/bloc/CommentBloc.java
src/main/java/com/high/highblog/bloc/JwtBloc.java
src/main/java/com/high/highblog/bloc/PostListBloc.java
src/main/java/com/high/highblog/mapper/CommentMapper.java
src/main/java/com/high/highblog/mapper/PostMapper.java
src/main/java/com/high/highblog/model/dto/response/CommentRes.java
src/main/java/com/high/highblog/model/dto/response/UserRes.java
src/main/java/com/high/highblog/model/entity/Comment.java
src/main/java/com/high/highblog/repository/CommentRepository.java
src/main/java/com/high/highblog/service/CommentService.java
src/main/resources/config/liquibase_ext/changelog/20210328143200_changelog.xml
src/main/resources/config/liquibase_ext/master.xml

- Writed change log to init comment table
- Created api to fetch list comment by post id

[BE][VIEWER] Create api to fetch list comment for current post

---

src/main/java/com/high/highblog/api/common/CommentListController.java
src/main/java/com/high/highblog/api/user/CommentCrudController.java
src/main/java/com/high/highblog/bloc/CommentBloc.java
src/main/java/com/high/highblog/mapper/CommentMapper.java
src/main/java/com/high/highblog/model/dto/request/CommentCreateReq.java
src/main/java/com/high/highblog/model/dto/request/CommentListReq.java
src/main/java/com/high/highblog/model/entity/Comment.java
src/main/java/com/high/highblog/repository/CommentRepository.java
src/main/java/com/high/highblog/service/CommentService.java

- Create api to add comment for a post
- Update api to fetch list comment for a post

[BE][USER] Create api to add comment for a post

---

src/main/java/com/high/highblog/api/user/CommentCrudController.java
src/main/java/com/high/highblog/bloc/CommentBloc.java
src/main/java/com/high/highblog/mapper/CommentMapper.java
src/main/java/com/high/highblog/model/dto/request/CommentUpdateReq.java
src/main/java/com/high/highblog/model/entity/Post.java
src/main/java/com/high/highblog/repository/CommentRepository.java
src/main/java/com/high/highblog/service/CommentService.java
src/main/java/com/high/highblog/service/PostService.java

- Create api to update comment
- Update api create comment to return id

[BE][USER] Create api to update comment

---

src/main/java/com/high/highblog/api/user/CommentCrudController.java
src/main/java/com/high/highblog/bloc/CommentBloc.java
src/main/java/com/high/highblog/model/dto/request/CommentUpdateReq.java
src/main/java/com/high/highblog/service/CommentService.java

- Create api to delete comment

[BE][USER] Create api to delete comment

---

src/main/java/com/high/highblog/api/user/PostCrudController.java
src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/service/PostService.java
src/main/java/com/high/highblog/service/PostTagService.java

[BE][USER] Create api to delete post

---

src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/bloc/PostListBloc.java
src/main/java/com/high/highblog/error/handler/ExceptionHandlerFilter.java
src/main/java/com/high/highblog/helper/PaginationHelper.java
src/main/java/com/high/highblog/mapper/PostMapper.java
src/main/java/com/high/highblog/model/dto/response/PostRes.java
src/main/java/com/high/highblog/model/entity/Post.java
src/main/java/com/high/highblog/model/entity/PostStatistic.java
src/main/java/com/high/highblog/repository/PostRepository.java
src/main/java/com/high/highblog/repository/PostStatisticRepository.java
src/main/java/com/high/highblog/service/PostService.java
src/main/java/com/high/highblog/service/PostStatisticService.java
src/main/resources/config/liquibase/changelog/20210329155600_changelog.xml
src/main/resources/config/liquibase_ext/changelog/20210329145900_changelog.xml
src/main/resources/config/liquibase_ext/master.xml

- Create add post_statistics change log
- Update Create, Fetch, Search post to interact with number of votes in post_statistics

[BE][USER] Update api to sort post by number of vote in post statistics

---

src/main/java/com/high/highblog/api/user/PostVoteCrudController.java
src/main/java/com/high/highblog/bloc/PostVoteCrudBloc.java
src/main/java/com/high/highblog/enums/VoteType.java
src/main/java/com/high/highblog/mapper/PostVoteMapper.java
src/main/java/com/high/highblog/model/dto/request/PostVoteCreateReq.java
src/main/java/com/high/highblog/model/dto/request/PostVoteUpdateReq.java
src/main/java/com/high/highblog/model/entity/PostVote.java
src/main/java/com/high/highblog/repository/PostStatisticRepository.java
src/main/java/com/high/highblog/repository/PostVoteRepository.java
src/main/java/com/high/highblog/service/PostStatisticService.java
src/main/java/com/high/highblog/service/PostVoteService.java
src/main/resources/config/liquibase_ext/changelog/20210330213200_changelog.xml
src/main/resources/config/liquibase_ext/master.xml

- Create api to create post vote
- Create api to upadate post vote

[BE][USER] Create api to upvote/downvote vote post

---

src/main/java/com/high/highblog/api/user/PostVoteCrudController.java
src/main/java/com/high/highblog/bloc/PostVoteCrudBloc.java
src/main/java/com/high/highblog/model/dto/request/PostVoteDeleteReq.java
src/main/java/com/high/highblog/service/PostStatisticService.java
src/main/java/com/high/highblog/service/PostVoteService.java

- Create api to delete post vote

[BE][USER] Create api to delete post vote

---

src/main/java/com/high/highblog/api/common/PostListController.java
src/main/java/com/high/highblog/bloc/PostListBloc.java
src/main/java/com/high/highblog/repository/PostRepository.java
src/main/java/com/high/highblog/service/PostService.java

- Create api to fetch list post of user

[BE][VIEWER] Create api to fetch list post of user

---

src/main/java/com/high/highblog/api/user/FavoritePostCrudController.java
src/main/java/com/high/highblog/bloc/FavoritePostCrudBloc.java
src/main/java/com/high/highblog/repository/FavoritePostRepository.java
src/main/java/com/high/highblog/service/FavoritePostService.java

- Create api to delete post from favorite

[BE][USER] Create api to delete post from favorite

---

src/main/java/com/high/highblog/api/user/FavoritePostListController.java
src/main/java/com/high/highblog/bloc/FavoritePostListBloc.java
src/main/resources/config/liquibase/master.xml

- Create api fetch favorite posts

[BE][USER] Create api to fetch list favorite posts

---

.dockerignore
.gitignore
src/main/java/com/high/highblog/api/common/RegisterController.java
src/main/java/com/high/highblog/api/user/FileUploadController.java
src/main/java/com/high/highblog/api/user/FileUploadListController.java
src/main/java/com/high/highblog/bloc/FileUploadListBloc.java
src/main/java/com/high/highblog/mapper/FileMapper.java
src/main/java/com/high/highblog/model/dto/response/ImageUploadRes.java
src/main/java/com/high/highblog/repository/FileRepository.java
src/main/java/com/high/highblog/service/FileService.java

- Create api to fetch list images

[BE][USER] Create api to fetch list images

---

src/main/java/com/high/highblog/api/user/FileCrudController.java
src/main/java/com/high/highblog/api/user/FileListController.java
src/main/java/com/high/highblog/api/user/PostCrudController.java
src/main/java/com/high/highblog/api/user/SubscriptionCrudController.java
src/main/java/com/high/highblog/bloc/FileCrudBloc.java
src/main/java/com/high/highblog/bloc/FileListBloc.java
src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/bloc/SubscriptionCrudBloc.java
src/main/java/com/high/highblog/model/entity/Subscription.java
src/main/java/com/high/highblog/repository/SubscriptionRepository.java
src/main/java/com/high/highblog/repository/UserRepository.java
src/main/java/com/high/highblog/service/SubscriptionService.java
src/main/java/com/high/highblog/service/UserService.java
src/main/resources/config/liquibase/changelog/20210409224700_changelog.xml
src/main/resources/config/liquibase/master.xml
src/main/resources/config/liquibase_ext/changelog/20210409224000_changelog.xml
src/main/resources/config/liquibase_ext/master.xml

- Create api to follow user
- Rename classes relate to FileUpload

[BE][USER] Create api to follow user

---

src/main/java/com/high/highblog/api/common/PostListController.java
src/main/java/com/high/highblog/api/user/SubscriptionCrudController.java
src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/bloc/PostListBloc.java
src/main/java/com/high/highblog/bloc/SubscriptionCrudBloc.java
src/main/java/com/high/highblog/model/dto/request/SubscriptionCreateReq.java
src/main/java/com/high/highblog/repository/PostRepository.java
src/main/java/com/high/highblog/repository/SubscriptionRepository.java
src/main/java/com/high/highblog/service/PostService.java
src/main/java/com/high/highblog/service/PostStatisticService.java
src/main/java/com/high/highblog/service/SubscriptionService.java

- Create api to unfollow user
- Update api post detail to return number of votes

[BE][USER] Create api to unfollow user

---

src/main/java/com/high/highblog/model/dto/request/RegisterReq.java
src/main/java/com/high/highblog/model/dto/response/UserRes.java

- Update api register to add and validate nick name

[BE][VIEWER] Update api register to add and validate nick name

---

src/main/java/com/high/highblog/api/common/GetUserDetailController.java
src/main/java/com/high/highblog/bloc/UserDetailBloc.java

- Created api to get user detail

[BE][VIEWER] Create api to get user detail

---

src/main/java/com/high/highblog/api/common/UserCrudController.java
src/main/java/com/high/highblog/api/user/PostListController.java
src/main/java/com/high/highblog/api/user/SubscriptionCrudController.java
src/main/java/com/high/highblog/bloc/PostListBloc.java
src/main/java/com/high/highblog/repository/PostRepository.java
src/main/java/com/high/highblog/repository/SubscriptionRepository.java
src/main/java/com/high/highblog/service/PostService.java

- Created api to fetch list posts from user followed

[BE][USER] Create api to fetch list post from user followed

---

src/main/java/com/high/highblog/api/common/RegisterController.java
src/main/java/com/high/highblog/api/common/UserCrudController.java
src/main/java/com/high/highblog/bloc/RegisterBloc.java
src/main/java/com/high/highblog/bloc/UserCrudBloc.java
src/main/java/com/high/highblog/constant/Constant.java
src/main/java/com/high/highblog/helper/CodeHelper.java
src/main/java/com/high/highblog/model/dto/request/ResendEmailReq.java
src/main/java/com/high/highblog/model/entity/ConfirmationCode.java
src/main/java/com/high/highblog/repository/ConfirmationCodeRepository.java
src/main/java/com/high/highblog/service/ConfirmationCodeService.java
src/main/resources/config/liquibase/changelog/20210411165400_changelog.xml
src/main/resources/config/liquibase/master.xml

- Create api to resend confirmation email
- Update register api to set cookie

[BE][VIEWER] Create api to resend confirmation email

---

build.gradle
gradle.properties
src/main/java/com/high/highblog/api/user/PaypalPaymentController.java
src/main/java/com/high/highblog/bloc/RegisterBloc.java
src/main/java/com/high/highblog/bloc/payment/PaypalPaymentBloc.java
src/main/java/com/high/highblog/config/ApplicationConfigProperties.java
src/main/java/com/high/highblog/config/PaypalConfig.java
src/main/java/com/high/highblog/model/dto/request/PaypalPaymentCreateReq.java
src/main/java/com/high/highblog/model/dto/request/RegisterReq.java
src/main/java/com/high/highblog/service/AccountService.java
src/main/resources/application.yml

- Init paypal config
- Update email pattern when register

[BE][USER] Init paypal config

---

src/main/java/com/high/highblog/bloc/MailBloc.java
src/main/java/com/high/highblog/config/WebConfig.java
src/main/java/com/high/highblog/model/dto/request/RegisterReq.java
src/main/java/com/high/highblog/model/dto/request/ResendEmailReq.java
src/main/java/com/high/highblog/model/entity/User.java
src/main/java/com/high/highblog/service/AccountService.java

- Fix bug async task when send email
- Fix validate bug for registration

[BE][USER] Fix bug async task when send email

---

src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/bloc/PostVoteCrudBloc.java
src/main/java/com/high/highblog/model/dto/request/PostVoteDeleteReq.java
src/main/java/com/high/highblog/model/entity/PostStatistic.java
src/main/java/com/high/highblog/model/entity/PostVote.java
src/main/java/com/high/highblog/service/PostStatisticService.java
src/main/java/com/high/highblog/service/PostVoteService.java

- Updated logic to update number of votes

[BE][USER] Fix bug update number of vote incorrectly

---

src/main/java/com/high/highblog/bloc/FavoritePostCrudBloc.java
src/main/java/com/high/highblog/service/PostVoteService.java

- Update validate function when user add a post to favorite

[BE][USER] Fix bug always already vote when add post to favorite

---

src/main/java/com/high/highblog/api/user/AccountCrudController.java
src/main/java/com/high/highblog/bloc/AccountCrudBloc.java
src/main/java/com/high/highblog/model/dto/request/PasswordUpdateReq.java
src/main/java/com/high/highblog/service/AccountService.java
src/main/java/com/high/highblog/service/PostVoteService.java
src/main/resources/application.yml

- Created api to change password

[BE][USER] Create api to change password

---

src/main/java/com/high/highblog/bloc/ProfileBloc.java
src/main/java/com/high/highblog/model/dto/response/ProfileRes.java

- Update api profile to return user id

[BE][USER] Update api profile api to return user id

---

src/main/java/com/high/highblog/api/user/FileCrudController.java
src/main/java/com/high/highblog/api/user/FileListController.java
src/main/java/com/high/highblog/bloc/FileCrudBloc.java
src/main/java/com/high/highblog/bloc/payment/PaypalDepositBloc.java
src/main/java/com/high/highblog/constant/Constant.java
src/main/java/com/high/highblog/helper/FileHelper.java
src/main/java/com/high/highblog/mapper/FileMapper.java
src/main/java/com/high/highblog/model/dto/request/FileReq.java
src/main/java/com/high/highblog/model/dto/response/FileRes.java
src/main/java/com/high/highblog/repository/FileRepository.java
src/main/java/com/high/highblog/repository/WalletRepository.java
src/main/java/com/high/highblog/service/FileService.java
src/main/java/com/high/highblog/service/WalletService.java

[BE][USER] Create api to delete image

---

src/main/java/com/high/highblog/model/entity/PostStatistic.java
src/main/resources/config/liquibase/changelog/20210420141800_changelog.xml
src/main/resources/config/liquibase/master.xml

- Added columns to save number of comments and favorites

[BE][DB] Add columns to save number of comments and favorites

---

src/main/java/com/high/highblog/bloc/FavoritePostCrudBloc.java
src/main/java/com/high/highblog/service/PostStatisticService.java

- Updated api crud to update number of favorites

[BE][USER] Update api crud to update number of favorites

---

src/main/java/com/high/highblog/api/common/CommentListController.java
src/main/java/com/high/highblog/api/user/CommentCrudController.java
src/main/java/com/high/highblog/bloc/CommentCrudBloc.java
src/main/java/com/high/highblog/bloc/CommentListBloc.java
src/main/java/com/high/highblog/mapper/PostMapper.java
src/main/java/com/high/highblog/model/dto/response/PostDetailRes.java
src/main/java/com/high/highblog/model/dto/response/PostRes.java
src/main/java/com/high/highblog/service/PostStatisticService.java

- Updated comment apis to update number of comments

[BE][USER] Update comment apis to update number of comments

---

src/main/java/com/high/highblog/api/user/DonationController.java
src/main/java/com/high/highblog/bloc/FavoritePostListBloc.java
src/main/java/com/high/highblog/bloc/RegisterBloc.java
src/main/java/com/high/highblog/bloc/payment/DonationBloc.java
src/main/java/com/high/highblog/enums/PaymentMethod.java
src/main/java/com/high/highblog/enums/PaymentType.java
src/main/java/com/high/highblog/error/handler/ExceptionHandlerFilter.java
src/main/java/com/high/highblog/model/dto/request/DonationReq.java
src/main/java/com/high/highblog/repository/WalletRepository.java
src/main/java/com/high/highblog/service/WalletService.java
src/main/java/com/high/highblog/service/payment/PaypalPaymentService.java

- Create api to donate
- Add user to favorite post res

[BE][USER] Create api to donate

---

src/main/java/com/high/highblog/bloc/payment/DonationBloc.java

- Update api to donate to validate insufficient wallet

[BE][USER] Update api to donate to validate insufficient wallet

---

build.gradle
gradle.properties
src/main/java/com/high/highblog/api/user/PaypalDepositController.java
src/main/java/com/high/highblog/api/user/PaypalWithdrawalController.java
src/main/java/com/high/highblog/bloc/payment/DonationBloc.java
src/main/java/com/high/highblog/bloc/payment/PaypalDepositBloc.java
src/main/java/com/high/highblog/bloc/payment/PaypalWithdrawalBloc.java
src/main/java/com/high/highblog/bloc/payment/TransactionBloc.java
src/main/java/com/high/highblog/enums/ThirdPartyTransactionStatus.java
src/main/java/com/high/highblog/model/dto/request/PaypalWithdrawReq.java
src/main/java/com/high/highblog/model/entity/ThirdPartyTransaction.java
src/main/java/com/high/highblog/service/UserTransactionService.java
src/main/java/com/high/highblog/service/WalletService.java
src/main/java/com/high/highblog/service/payment/PaymentService.java
src/main/java/com/high/highblog/service/payment/PaypalPaymentService.java

- Create api to withdraw to paypal account
- Update logic to update wallet balance

[BE][USER] Create api to withdraw to paypal account

---

src/main/java/com/high/highblog/api/common/RegisterController.java
src/main/java/com/high/highblog/bloc/RegisterBloc.java
src/main/java/com/high/highblog/repository/UserRepository.java
src/main/java/com/high/highblog/service/ConfirmationCodeService.java
src/main/java/com/high/highblog/service/UserService.java
src/main/java/com/high/highblog/service/WalletService.java

- Update api register to init wallet
- Update validate in resend email and verify confirmation code

[BE][USER] Update api register to init wallet

---

src/main/java/com/high/highblog/config/SecurityConfig.java
src/main/java/com/high/highblog/config/ServerConfig.java
src/main/resources/application.yml

[BE][USER] Config https

---

src/main/java/com/high/highblog/bloc/payment/PaypalDepositBloc.java
src/main/java/com/high/highblog/bloc/payment/PaypalWithdrawalBloc.java
src/main/java/com/high/highblog/bloc/payment/TransactionBloc.java
src/main/java/com/high/highblog/config/WebConfig.java

- Fix bug api withdrawth to update payment type correctly

[BE][USER] Fix bug api withdraw to update payment type correctly

---

auto_deploy_bash
src/main/java/com/high/highblog/bloc/JwtBloc.java
src/main/java/com/high/highblog/bloc/ProfileBloc.java
src/main/java/com/high/highblog/bloc/notification/NotificationBloc.java
src/main/java/com/high/highblog/config/SecurityConfig.java
src/main/java/com/high/highblog/config/WebConfig.java
src/main/java/com/high/highblog/mapper/CommentMapper.java
src/main/java/com/high/highblog/mapper/UserMapper.java
src/main/java/com/high/highblog/model/dto/response/NotificationRes.java
src/main/java/com/high/highblog/model/dto/response/UserRes.java
src/main/java/com/high/highblog/model/entity/Notification.java
src/main/java/com/high/highblog/security/JwtFilter.java
src/main/resources/application.yml
src/main/resources/config/liquibase/changelog/20210510110800_changelog.xml
src/main/resources/config/liquibase/master.xml

- Add sender id field to notification table

[BE][DB] Add sender id field to notification table

---

src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/model/dto/request/PostSearchReq.java
src/main/java/com/high/highblog/model/dto/response/UserRes.java
src/main/java/com/high/highblog/model/entity/User.java
src/main/java/com/high/highblog/repository/NotificationRepository.java
src/main/java/com/high/highblog/service/SubscriptionService.java

- Updated api fetch post detail to return notified status

[BE][USER] Update api fetch post detail to return notified status

---

src/main/java/com/high/highblog/api/admin/PostListController.java
src/main/java/com/high/highblog/bloc/admin/PostListBloc.java
src/main/java/com/high/highblog/model/dto/request/admin/AdminPostSearchReq.java
src/main/java/com/high/highblog/repository/PostRepository.java
src/main/java/com/high/highblog/service/PostService.java

- Updated api search post to support dynamic search

[BE][ADMIN] Update api search post to support dynamic search

---

src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/bloc/UserCrudBloc.java
src/main/java/com/high/highblog/model/dto/response/UserDetailRes.java
src/main/java/com/high/highblog/model/entity/User.java

- Update api get user detail to show followed status

[BE][USER] Update api get user detail to show followed status

---

src/main/java/com/high/highblog/api/common/UserCrudController.java
src/main/java/com/high/highblog/bloc/UserCrudBloc.java
src/main/java/com/high/highblog/mapper/UserMapper.java
src/main/java/com/high/highblog/model/dto/response/UserDetailRes.java
src/main/java/com/high/highblog/repository/SubscriptionRepository.java
src/main/java/com/high/highblog/service/SubscriptionService.java

- Updated api get user detail to return number of followers

[BE][VIEWER] Update api get user detail to return number of followers

---

src/main/java/com/high/highblog/bloc/PostListBloc.java
src/main/java/com/high/highblog/repository/PostRepository.java
src/main/java/com/high/highblog/service/PostService.java

- Updated logic to sort post by numberOfVotes and createdDate

[BE][VIEWER] Update logic to sort post by numberOfVotes and createdDate

---

src/main/java/com/high/highblog/api/admin/SystemTransactionController.java
src/main/java/com/high/highblog/bloc/UserTransactionBloc.java
src/main/java/com/high/highblog/bloc/admin/SystemTransactionBloc.java
src/main/java/com/high/highblog/config/SecurityConfig.java
src/main/java/com/high/highblog/model/dto/request/admin/SystemTransactionReq.java
src/main/java/com/high/highblog/model/dto/response/admin/SystemTransactionRes.java
src/main/java/com/high/highblog/model/entity/SystemTransaction.java
src/main/java/com/high/highblog/repository/SystemTransactionRepository.java
src/main/java/com/high/highblog/service/SystemTransactionService.java

- Create api to fetch list third-party transaction by user
- Authorize admin api

[BE][ADMIN] Create api to fetch list third-party transaction by user

---

src/main/java/com/high/highblog/api/admin/PaypalReportingController.java
src/main/java/com/high/highblog/bloc/admin/PaypalReportingBloc.java
src/main/java/com/high/highblog/external/paypal/dto/reporting/Balance.java
src/main/java/com/high/highblog/external/paypal/dto/reporting/Currency.java
src/main/java/com/high/highblog/external/paypal/dto/reporting/ReportingBalanceRequest.java
src/main/java/com/high/highblog/external/paypal/dto/reporting/ReportingBalanceResponse.java
src/main/java/com/high/highblog/model/dto/response/admin/AdminBalanceRes.java

- Created api to get paypal balances
- Create balance request and response object like paypal sdk

[BE][ADMIN] Create api to get paypal balances

---

src/main/java/com/high/highblog/api/auth/AuthController.java
src/main/java/com/high/highblog/api/common/RegisterController.java
src/main/java/com/high/highblog/config/WebConfig.java
src/main/java/com/high/highblog/error/handler/GlobalExceptionHandler.java
src/main/java/com/high/highblog/model/dto/request/RegisterReq.java

- Update exception handler to support @Valid annotation

[BE] Update exception handler

---

src/main/java/com/high/highblog/bloc/UserCrudBloc.java
src/main/java/com/high/highblog/model/dto/request/LoginReq.java

- Return notified status in user detail

[BE][USER] Return nofied status in user detail

---

src/main/java/com/high/highblog/api/admin/NotificationCrudController.java
src/main/java/com/high/highblog/api/common/CommentListController.java
src/main/java/com/high/highblog/bloc/admin/NotificationCrudBloc.java
src/main/java/com/high/highblog/config/WebConfig.java
src/main/java/com/high/highblog/enums/NotificationType.java
src/main/java/com/high/highblog/model/dto/request/admin/NotificationCreateReq.java

- Create api to push notification for admin

[BE][ADMIN] Create api to push notification for admin

---

src/main/java/com/high/highblog/repository/PostRepository.java

- Fix buug for soritng list posts

[BE][VIEWER] Fix bug for sorting list posts

---

auto_deploy_bash
src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/bloc/notification/NotificationBloc.java
src/main/java/com/high/highblog/repository/PostRepository.java

[BE][USER] Add search by regexp

---

auto_deploy_bash
src/main/java/com/high/highblog/api/user/UserCrudController.java
src/main/resources/application.yml

- Update missing extension of image

[BE][USER] Update missing extension of image

---

src/main/java/com/high/highblog/bloc/admin/PostListBloc.java
src/main/java/com/high/highblog/service/PostService.java

[BE][USER] Update post list logic

---

src/main/java/com/high/highblog/bloc/admin/PostListBloc.java
src/main/java/com/high/highblog/model/dto/response/admin/SystemTransactionRes.java
src/main/java/com/high/highblog/security/CustomUserDetailsService.java

- Throw exception for locked user

[BE][USER] Throw exception for locked user

---

src/main/java/com/high/highblog/api/admin/TagCrudController.java
src/main/java/com/high/highblog/bloc/admin/TagCrudBloc.java
src/main/java/com/high/highblog/model/dto/request/admin/AdminUpdateTagReq.java
src/main/java/com/high/highblog/model/entity/File.java
src/main/java/com/high/highblog/service/TagService.java
src/main/resources/config/liquibase_ext/changelog/20210725180600_changelog.xml
src/main/resources/config/liquibase_ext/master.xml

create api to update tag
Fix bug cannot save files with names longer than 50 characters

[BE][ADMIN] create api to update tag

---

src/main/java/com/high/highblog/bloc/PostCrudBloc.java
src/main/java/com/high/highblog/config/WebConfig.java
src/main/java/com/high/highblog/service/PostService.java

- Add validation when get post detail

[BE][USER] Cannot get draft post detail
